import { useState, useEffect } from 'react'
import { Routes, Route, useNavigate, useParams } from 'react-router-dom'
import ReactMarkdown from 'react-markdown'
import remarkGfm from 'remark-gfm'
import remarkMath from 'remark-math'
import rehypeKatex from 'rehype-katex'
import CodeViewer from './CodeViewer'

interface Proposal {
  id: string
  filename: string
  title?: string
  status?: string
  priority?: string
  created?: string
  based_on?: string
  modified: number
  experiment_number?: string
  experiment_log?: boolean
  results_file?: boolean
  code_available?: boolean
}

interface ProposalsViewProps {
  sseUrl: string
}

// Proposals List Component
function ProposalsList({ sseUrl }: ProposalsViewProps) {
  const navigate = useNavigate()
  const [proposals, setProposals] = useState<Proposal[]>([])
  const [loading, setLoading] = useState(true)
  const [filter, setFilter] = useState<{ status?: string; priority?: string }>({})
  const [activeExperiments, setActiveExperiments] = useState<Set<string>>(new Set())

  // Fetch active experiments
  useEffect(() => {
    const fetchActiveWork = async () => {
      try {
        const res = await fetch(`${sseUrl}/api/status`)
        if (res.ok) {
          const data = await res.json()
          const activeIds = new Set(Object.keys(data.active_work?.active_work || {}))
          setActiveExperiments(activeIds)
        }
      } catch (err) {
        console.error('Error fetching active work:', err)
      }
    }

    fetchActiveWork()
    const interval = setInterval(fetchActiveWork, 30000)
    return () => clearInterval(interval)
  }, [sseUrl])

  // Fetch proposals list
  useEffect(() => {
    const fetchProposals = async () => {
      try {
        const res = await fetch(`${sseUrl}/api/proposals`)
        if (res.ok) {
          const data = await res.json()
          setProposals(data.proposals || [])
        }
      } catch (err) {
        console.error('Error fetching proposals:', err)
      } finally {
        setLoading(false)
      }
    }

    fetchProposals()
  }, [sseUrl])

  // Filter proposals
  const filteredProposals = proposals.filter(p => {
    if (filter.status && p.status !== filter.status) return false
    if (filter.priority && p.priority !== filter.priority) return false
    return true
  })

  // Get unique values for filters
  const statuses = [...new Set(proposals.map(p => p.status).filter(Boolean))]
  const priorities = [...new Set(proposals.map(p => p.priority).filter(Boolean))]

  if (loading) {
    return (
      <div className="bg-gray-50 p-6 rounded-lg text-center text-gray-500">
        Loading proposals...
      </div>
    )
  }

  return (
    <div className="space-y-4">
      {/* About Proposals */}
      <div className="bg-green-50 border border-green-200 rounded-lg p-4">
        <h3 className="text-sm font-semibold text-gray-900 mb-2">What are Proposals?</h3>
        <p className="text-sm text-gray-700 mb-2">
          Proposals are novel neural architecture designs autonomously generated by the <strong>Research Agent</strong>.
          Each proposal describes a specific architectural innovation—typically variations on linear attention,
          state-space models, or efficient sequence modeling techniques.
        </p>
        <p className="text-sm text-gray-700">
          The Research Agent analyzes recent papers, existing implementations, and experimental results to generate
          proposals that combine promising ideas in novel ways. Proposals include mathematical formulations,
          computational complexity analysis, and implementation specifications. Selected proposals are then
          handed off to Experiment Agents for implementation and evaluation.
        </p>
      </div>

      {/* Filters */}
      <div className="flex gap-4 items-center text-sm">
        <div>
          <label className="text-gray-600 mr-2">Status:</label>
          <select
            value={filter.status || ''}
            onChange={(e) => setFilter({ ...filter, status: e.target.value || undefined })}
            className="border border-gray-300 rounded px-2 py-1"
          >
            <option value="">All</option>
            {statuses.map(s => (
              <option key={s} value={s}>{s}</option>
            ))}
          </select>
        </div>

        <div>
          <label className="text-gray-600 mr-2">Priority:</label>
          <select
            value={filter.priority || ''}
            onChange={(e) => setFilter({ ...filter, priority: e.target.value || undefined })}
            className="border border-gray-300 rounded px-2 py-1"
          >
            <option value="">All</option>
            {priorities.map(p => (
              <option key={p} value={p}>{p}</option>
            ))}
          </select>
        </div>

        <div className="ml-auto text-gray-500">
          {filteredProposals.length} proposal{filteredProposals.length !== 1 ? 's' : ''}
        </div>
      </div>

      {/* Proposals Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
        {filteredProposals.map(proposal => (
          <button
            key={proposal.id}
            onClick={() => navigate(`/mad/proposals/${proposal.id}`)}
            className="text-left p-4 border border-gray-200 rounded-lg hover:shadow-md transition-shadow"
          >
            <div className="space-y-2">
              <div className="font-mono text-xs text-gray-500">{proposal.id}</div>

              <h3 className="font-medium text-gray-900 line-clamp-2">
                {proposal.title || proposal.id}
              </h3>

              <div className="flex gap-2 flex-wrap">
                {proposal.status && (
                  <span className={`px-2 py-0.5 rounded text-xs font-medium ${
                    proposal.status === 'proposed' ? 'bg-blue-100 text-blue-800' :
                    proposal.status === 'implemented' ? 'bg-green-100 text-green-800' :
                    proposal.status === 'in-progress' ? 'bg-yellow-100 text-yellow-800' :
                    'bg-gray-100 text-gray-800'
                  }`}>
                    {proposal.status}
                  </span>
                )}

                {proposal.priority && (
                  <span className={`px-2 py-0.5 rounded text-xs font-medium ${
                    proposal.priority === 'high' ? 'bg-red-100 text-red-800' :
                    proposal.priority === 'medium' ? 'bg-orange-100 text-orange-800' :
                    'bg-gray-100 text-gray-800'
                  }`}>
                    {proposal.priority}
                  </span>
                )}
              </div>

              {proposal.created && (
                <div className="text-xs text-gray-500">
                  Created: {proposal.created}
                </div>
              )}

              {/* Experiment artifacts indicators */}
              {(proposal.code_available || proposal.experiment_log || proposal.results_file) && (
                <div className="flex gap-1.5 text-xs mt-2 flex-wrap">
                  {proposal.code_available && (
                    <span className="px-2 py-0.5 bg-green-50 text-green-700 rounded border border-green-200">
                      💻 Code
                    </span>
                  )}
                  {proposal.experiment_log && (
                    <span className="px-2 py-0.5 bg-blue-50 text-blue-700 rounded border border-blue-200">
                      📝 Log
                    </span>
                  )}
                  {proposal.results_file && (
                    <span className="px-2 py-0.5 bg-purple-50 text-purple-700 rounded border border-purple-200">
                      📊 Results
                    </span>
                  )}
                </div>
              )}

              {/* Active indicator */}
              {activeExperiments.has(proposal.id) && (
                <div className="flex items-center gap-1.5 text-xs mt-2 text-yellow-700">
                  <div className="w-1.5 h-1.5 rounded-full bg-yellow-500 animate-pulse" />
                  <span className="font-medium">Running</span>
                </div>
              )}
            </div>
          </button>
        ))}
      </div>

      {filteredProposals.length === 0 && (
        <div className="bg-gray-50 p-8 rounded-lg text-center text-gray-500">
          No proposals match the selected filters
        </div>
      )}
    </div>
  )
}

// Proposal Detail Component
function ProposalDetail({ sseUrl }: ProposalsViewProps) {
  const navigate = useNavigate()
  const { proposalId } = useParams<{ proposalId: string }>()

  const [proposals, setProposals] = useState<Proposal[]>([])
  const [proposalContent, setProposalContent] = useState<string>('')
  const [experimentLog, setExperimentLog] = useState<string>('')
  const [experimentResults, setExperimentResults] = useState<string>('')
  const [wandbUrl, setWandbUrl] = useState<string | null>(null)
  const [codeAvailable, setCodeAvailable] = useState(false)
  const [activeExperiments, setActiveExperiments] = useState<Set<string>>(new Set())
  const [viewMode, setViewMode] = useState<'proposal' | 'log' | 'results' | 'code'>('proposal')

  // Fetch proposals metadata
  useEffect(() => {
    const fetchProposals = async () => {
      try {
        const res = await fetch(`${sseUrl}/api/proposals`)
        if (res.ok) {
          const data = await res.json()
          setProposals(data.proposals || [])
        }
      } catch (err) {
        console.error('Error fetching proposals:', err)
      }
    }
    fetchProposals()
  }, [sseUrl])

  // Fetch active experiments
  useEffect(() => {
    const fetchActiveWork = async () => {
      try {
        const res = await fetch(`${sseUrl}/api/status`)
        if (res.ok) {
          const data = await res.json()
          const activeIds = new Set(Object.keys(data.active_work?.active_work || {}))
          setActiveExperiments(activeIds)
        }
      } catch (err) {
        console.error('Error fetching active work:', err)
      }
    }
    fetchActiveWork()
  }, [sseUrl])

  // Check if code is available
  useEffect(() => {
    if (proposalId) {
      const experimentNumber = proposalId.split('-')[0]
      const checkCodeAvailable = async () => {
        try {
          const res = await fetch(`${sseUrl}/api/experiment-code/${experimentNumber}`)
          setCodeAvailable(res.ok)
        } catch (err) {
          setCodeAvailable(false)
        }
      }
      checkCodeAvailable()
    }
  }, [proposalId, sseUrl])

  // Fetch proposal content
  useEffect(() => {
    if (!proposalId) return

    const fetchContent = async () => {
      try {
        const res = await fetch(`${sseUrl}/api/proposal/${proposalId}`)
        if (res.ok) {
          const data = await res.json()
          setProposalContent(data.content || '')
        }
      } catch (err) {
        console.error('Error fetching proposal content:', err)
      }
    }

    fetchContent()
  }, [proposalId, sseUrl])

  // Extract wandb URL from markdown content
  const extractWandbUrl = (content: string): string | null => {
    const wandbMatch = content.match(/https:\/\/wandb\.ai\/[^\s)]+/i)
    return wandbMatch ? wandbMatch[0] : null
  }

  // Fetch experiment results
  const fetchExperimentResults = async (experimentNumber: string) => {
    try {
      const res = await fetch(`${sseUrl}/api/result/${experimentNumber}`)
      if (res.ok) {
        const data = await res.json()
        const content = data.content || ''
        setExperimentResults(content)
        setWandbUrl(extractWandbUrl(content))
      }
    } catch (err) {
      console.error('Error fetching experiment results:', err)
    }
  }

  // Fetch experiment log
  const fetchExperimentLog = async (experimentNumber: string) => {
    try {
      const res = await fetch(`${sseUrl}/api/experiment-log/${experimentNumber}`)
      if (res.ok) {
        const data = await res.json()
        const content = data.content || ''
        setExperimentLog(content)
        setWandbUrl(extractWandbUrl(content))
      }
    } catch (err) {
      console.error('Error fetching experiment log:', err)
    }
  }

  // Load log/results when navigating to those tabs
  useEffect(() => {
    if (!proposalId) return
    const experimentNumber = proposalId.split('-')[0]

    if (viewMode === 'log' && !experimentLog) {
      fetchExperimentLog(experimentNumber)
    } else if (viewMode === 'results' && !experimentResults) {
      fetchExperimentResults(experimentNumber)
    }
  }, [viewMode, proposalId])

  if (!proposalId) return null

  const currentProposal = proposals.find(p => p.id === proposalId)
  const isActive = activeExperiments.has(proposalId)
  const hasExperimentData = currentProposal?.experiment_log || currentProposal?.results_file || codeAvailable

  return (
    <div>
      <button
        onClick={() => navigate('/mad/proposals')}
        className="mb-4 text-blue-600 hover:text-blue-800 text-sm"
      >
        ← Back to proposals list
      </button>

      {/* Status Badge */}
      {isActive && (
        <div className="mb-4 inline-flex items-center gap-2 px-3 py-1.5 bg-yellow-50 border border-yellow-200 rounded-lg text-sm">
          <div className="w-2 h-2 rounded-full bg-yellow-500 animate-pulse" />
          <span className="text-yellow-800 font-medium">Experiment In Progress</span>
        </div>
      )}

      {/* Experiment links/tabs */}
      {currentProposal && hasExperimentData && (
        <div className="mb-4 flex gap-2 border-b border-gray-200 pb-2">
          <button
            onClick={() => setViewMode('proposal')}
            className={`px-3 py-1.5 text-sm font-medium rounded-t ${
              viewMode === 'proposal'
                ? 'bg-blue-600 text-white'
                : 'bg-gray-100 text-gray-700 hover:bg-gray-200'
            }`}
          >
            📄 Proposal
          </button>

          {codeAvailable && (
            <button
              onClick={() => setViewMode('code')}
              className={`px-3 py-1.5 text-sm font-medium rounded-t ${
                viewMode === 'code'
                  ? 'bg-blue-600 text-white'
                  : 'bg-gray-100 text-gray-700 hover:bg-gray-200'
              }`}
            >
              💻 Code
            </button>
          )}

          {currentProposal.experiment_log && (
            <button
              onClick={() => setViewMode('log')}
              className={`px-3 py-1.5 text-sm font-medium rounded-t ${
                viewMode === 'log'
                  ? 'bg-blue-600 text-white'
                  : 'bg-gray-100 text-gray-700 hover:bg-gray-200'
              }`}
            >
              📝 Experiment Log
            </button>
          )}

          {currentProposal.results_file && (
            <button
              onClick={() => setViewMode('results')}
              className={`px-3 py-1.5 text-sm font-medium rounded-t ${
                viewMode === 'results'
                  ? 'bg-blue-600 text-white'
                  : 'bg-gray-100 text-gray-700 hover:bg-gray-200'
              }`}
            >
              📊 Results
            </button>
          )}
        </div>
      )}

      {/* Wandb link display */}
      {wandbUrl && (viewMode === 'log' || viewMode === 'results') && (
        <div className="mb-4 p-4 bg-gradient-to-r from-orange-50 to-yellow-50 border border-orange-200 rounded-lg">
          <div className="flex items-center gap-3">
            <div className="text-2xl">📊</div>
            <div className="flex-1">
              <div className="font-semibold text-gray-900 text-sm">Weights & Biases Run</div>
              <div className="text-xs text-gray-600 mt-0.5">View training metrics, charts, and system stats</div>
            </div>
            <a
              href={wandbUrl}
              target="_blank"
              rel="noopener noreferrer"
              className="px-4 py-2 bg-orange-600 hover:bg-orange-700 text-white text-sm font-medium rounded-lg transition-colors"
            >
              Open W&B →
            </a>
          </div>
        </div>
      )}

      {/* Content display */}
      {viewMode === 'code' ? (
        <div
          className="border border-gray-200 rounded-lg overflow-hidden"
          style={{
            height: 'calc(100vh - 300px)',
            width: '100vw',
            marginLeft: 'calc(-50vw + 50%)',
            marginRight: 'calc(-50vw + 50%)',
            maxWidth: 'none'
          }}
        >
          <CodeViewer
            experimentId={proposalId}
            sseUrl={sseUrl}
            onClose={() => setViewMode('proposal')}
            embedded={true}
          />
        </div>
      ) : (
        <div className="prose prose-sm max-w-none">
          {viewMode === 'proposal' && (
            <ReactMarkdown
              remarkPlugins={[remarkGfm, remarkMath]}
              rehypePlugins={[rehypeKatex]}
            >
              {proposalContent}
            </ReactMarkdown>
          )}

          {viewMode === 'log' && experimentLog && (
            <ReactMarkdown
              remarkPlugins={[remarkGfm, remarkMath]}
              rehypePlugins={[rehypeKatex]}
            >
              {experimentLog}
            </ReactMarkdown>
          )}

          {viewMode === 'results' && experimentResults && (
            <ReactMarkdown
              remarkPlugins={[remarkGfm, remarkMath]}
              rehypePlugins={[rehypeKatex]}
            >
              {experimentResults}
            </ReactMarkdown>
          )}

          {viewMode === 'log' && !experimentLog && (
            <div className="text-gray-500 text-center py-8">Loading experiment log...</div>
          )}

          {viewMode === 'results' && !experimentResults && (
            <div className="text-gray-500 text-center py-8">Loading results...</div>
          )}
        </div>
      )}
    </div>
  )
}

// Main Router Component
export default function ProposalsView({ sseUrl }: ProposalsViewProps) {
  return (
    <Routes>
      <Route path="/" element={<ProposalsList sseUrl={sseUrl} />} />
      <Route path="/:proposalId" element={<ProposalDetail sseUrl={sseUrl} />} />
    </Routes>
  )
}
