import { useState, useEffect, useRef, Fragment } from 'react'
import { useNavigate, useLocation } from 'react-router-dom'
import ReactMarkdown from 'react-markdown'
import remarkGfm from 'remark-gfm'
import remarkMath from 'remark-math'
import rehypeKatex from 'rehype-katex'
import CodeViewer from './CodeViewer'

interface Proposal {
  id: string
  title?: string
  priority?: string
  created?: string
  based_on?: string
  has_mve?: boolean
}

interface ProposalsViewProps {
  apiUrl: string
}

// Proposals List Component
function ProposalsList({ apiUrl }: ProposalsViewProps) {
  const navigate = useNavigate()
  const [proposals, setProposals] = useState<Proposal[]>([])
  const [loading, setLoading] = useState(true)
  const [filter, setFilter] = useState<{ priority?: string }>({})

  // Fetch proposals list
  useEffect(() => {
    const fetchProposals = async () => {
      try {
        const res = await fetch(`${apiUrl}/proposals`)
        if (res.ok) {
          const proposals = await res.json()
          setProposals(proposals || [])
        }
      } catch (err) {
        console.error('Error fetching proposals:', err)
      } finally {
        setLoading(false)
      }
    }

    fetchProposals()
  }, [apiUrl])

  // Filter proposals
  const filteredProposals = proposals.filter(p => {
    if (filter.priority && p.priority !== filter.priority) return false
    return true
  })

  // Get unique values for filters
  const priorities = [...new Set(proposals.map(p => p.priority).filter(Boolean))]

  if (loading) {
    return (
      <div className="bg-gray-50 p-6 rounded-lg text-center text-gray-500">
        Loading proposals...
      </div>
    )
  }

  return (
    <div className="space-y-4">
      {/* About Proposals */}
      <div className="bg-green-50 border border-green-200 rounded-lg p-4">
        <h3 className="text-sm font-semibold text-gray-900 mb-2">What are Proposals?</h3>
        <p className="text-sm text-gray-700 mb-2">
          Proposals are novel neural architecture designs autonomously generated by the <strong>Research Agent</strong>.
          Each proposal describes a specific architectural innovation—typically variations on linear attention,
          state-space models, or efficient sequence modeling techniques.
        </p>
        <p className="text-sm text-gray-700">
          The Research Agent analyzes recent papers, existing implementations, and experimental results to generate
          proposals that combine promising ideas in novel ways. Proposals include mathematical formulations,
          computational complexity analysis, and implementation specifications. Selected proposals are then
          handed off to Experiment Agents for implementation and evaluation.
        </p>
      </div>

      {/* Filters */}
      <div className="flex gap-4 items-center text-sm">
        <div>
          <label className="text-gray-600 mr-2">Priority:</label>
          <select
            value={filter.priority || ''}
            onChange={(e) => setFilter({ ...filter, priority: e.target.value || undefined })}
            className="border border-gray-300 rounded px-2 py-1"
          >
            <option value="">All</option>
            {priorities.map(p => (
              <option key={p} value={p}>{p}</option>
            ))}
          </select>
        </div>

        <div className="ml-auto text-gray-500">
          {filteredProposals.length} proposal{filteredProposals.length !== 1 ? 's' : ''}
        </div>
      </div>

      {/* Proposals Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
        {filteredProposals.map(proposal => (
          <div
            key={proposal.id}
            className="text-left p-4 border border-gray-200 rounded-lg hover:shadow-md transition-shadow cursor-pointer"
            onClick={() => navigate(`/proposals/${proposal.id}`)}
          >
            <div className="space-y-2">
              <div className="font-mono text-xs text-gray-500">{proposal.id}</div>

              <h3 className="font-medium text-gray-900 line-clamp-2">
                {proposal.title || proposal.id}
              </h3>

              <div className="flex gap-2 flex-wrap">
                {proposal.priority && (
                  <span className={`px-2 py-0.5 rounded text-xs font-medium ${
                    proposal.priority === 'high' ? 'bg-red-100 text-red-800' :
                    proposal.priority === 'medium' ? 'bg-orange-100 text-orange-800' :
                    'bg-gray-100 text-gray-800'
                  }`}>
                    {proposal.priority}
                  </span>
                )}
              </div>

              {proposal.created && (
                <div className="text-xs text-gray-500">
                  Created: {proposal.created}
                </div>
              )}
            </div>
          </div>
        ))}
      </div>

      {filteredProposals.length === 0 && (
        <div className="bg-gray-50 p-8 rounded-lg text-center text-gray-500">
          No proposals match the selected filters
        </div>
      )}
    </div>
  )
}

interface ProposalDetailProps {
  apiUrl: string
  proposalId: string
}

interface ProposalExperiment {
  id: string
  proposal_id: string
  status: string
  worker_id?: string
  wandb_url?: string
  results?: Record<string, unknown>
  error?: string
  error_class?: string
  cost_actual?: number
  cost_estimate?: number
  created_at: string
  completed_at?: string
  run_number: number
}

interface ExperimentEvent {
  created_at: string
  type: string
  summary: string
  experiment_id?: string
  worker_id?: string
}

// Proposal Detail Component
function ProposalDetail({ apiUrl, proposalId }: ProposalDetailProps) {
  const navigate = useNavigate()

  const [proposalContent, setProposalContent] = useState<string>('')
  const [proposalExperiments, setProposalExperiments] = useState<ProposalExperiment[]>([])
  const [experimentsLoading, setExperimentsLoading] = useState(true)
  const [viewMode, setViewMode] = useState<'proposal' | 'experiments' | 'code'>('proposal')
  const [codeAvailable, setCodeAvailable] = useState(false)
  const [dispatching, setDispatching] = useState(false)
  const [dispatchResult, setDispatchResult] = useState<{ success: boolean; message: string } | null>(null)
  const [expandedExperimentId, setExpandedExperimentId] = useState<string | null>(null)
  const [experimentEvents, setExperimentEvents] = useState<ExperimentEvent[]>([])
  const [eventsLoading, setEventsLoading] = useState(false)
  const inlineLogRef = useRef<HTMLDivElement>(null)

  const fetchExperimentEvents = async (experimentId: string) => {
    setEventsLoading(true)
    try {
      const res = await fetch(`${apiUrl}/experiments/${experimentId}/events?limit=200`)
      if (res.ok) {
        setExperimentEvents(await res.json())
      }
    } catch (err) {
      console.error('Error fetching experiment events:', err)
    } finally {
      setEventsLoading(false)
    }
  }

  // SSE subscription for live log updates when inline panel is open
  useEffect(() => {
    if (!expandedExperimentId) return
    const es = new EventSource(`${apiUrl}/events/stream`)
    es.onmessage = (msg) => {
      try {
        const event = JSON.parse(msg.data)
        if (String(event.experiment_id) === expandedExperimentId) {
          setExperimentEvents(prev => [...prev, event])
          requestAnimationFrame(() => {
            if (inlineLogRef.current) {
              inlineLogRef.current.scrollTop = inlineLogRef.current.scrollHeight
            }
          })
        }
      } catch { /* ignore */ }
    }
    return () => es.close()
  }, [expandedExperimentId, apiUrl])

  const toggleExperimentLogs = (experimentId: string) => {
    if (expandedExperimentId === experimentId) {
      setExpandedExperimentId(null)
      setExperimentEvents([])
    } else {
      setExpandedExperimentId(experimentId)
      fetchExperimentEvents(experimentId)
    }
  }

  const dispatchExperiment = async () => {
    if (!proposalId) return
    setDispatching(true)
    setDispatchResult(null)
    try {
      const res = await fetch(`${apiUrl}/experiments`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ proposal_id: proposalId })
      })
      if (res.ok) {
        const data = await res.json()
        setDispatchResult({ success: true, message: `Experiment ${data.id} created` })
        // Refresh experiments list
        fetchExperiments()
      } else {
        const err = await res.json()
        setDispatchResult({ success: false, message: err.detail || 'Failed to dispatch' })
      }
    } catch (err) {
      setDispatchResult({ success: false, message: `Network error: ${err}` })
    } finally {
      setDispatching(false)
    }
  }

  // Fetch proposal content
  useEffect(() => {
    if (!proposalId) return
    const fetchContent = async () => {
      try {
        const res = await fetch(`${apiUrl}/proposals/${proposalId}`)
        if (res.ok) {
          const data = await res.json()
          setProposalContent(data.content || '')
        }
      } catch (err) {
        console.error('Error fetching proposal content:', err)
      }
    }
    fetchContent()
  }, [proposalId, apiUrl])

  // Fetch experiments for this proposal
  const fetchExperiments = async () => {
    setExperimentsLoading(true)
    try {
      const res = await fetch(`${apiUrl}/experiments?proposal_id=${encodeURIComponent(proposalId)}`)
      if (res.ok) {
        setProposalExperiments(await res.json())
      }
    } catch (err) {
      console.error('Error fetching experiments:', err)
    } finally {
      setExperimentsLoading(false)
    }
  }

  useEffect(() => {
    fetchExperiments()
  }, [proposalId, apiUrl])

  // Check if code is available
  useEffect(() => {
    if (proposalExperiments.length > 0) {
      const latestExpId = proposalExperiments[0].id
      const checkCodeAvailable = async () => {
        try {
          const res = await fetch(`${apiUrl}/experiments/${latestExpId}/code/tree`)
          setCodeAvailable(res.ok)
        } catch (err) {
          setCodeAvailable(false)
        }
      }
      checkCodeAvailable()
    }
  }, [proposalExperiments, apiUrl])

  if (!proposalId) return null

  const hasRunning = proposalExperiments.some(e => e.status === 'running')

  return (
    <div>
      <button
        onClick={() => navigate('/proposals')}
        className="mb-4 text-blue-600 hover:text-blue-800 text-sm"
      >
        ← Back to proposals list
      </button>

      {/* Status Badge */}
      {hasRunning && (
        <div className="mb-4 inline-flex items-center gap-2 px-3 py-1.5 bg-yellow-50 border border-yellow-200 rounded-lg text-sm">
          <div className="w-2 h-2 rounded-full bg-yellow-500 animate-pulse" />
          <span className="text-yellow-800 font-medium">Experiment In Progress</span>
        </div>
      )}

      {/* Dispatch button */}
      <div className="mb-4 flex items-center gap-3">
        <button
          onClick={dispatchExperiment}
          disabled={dispatching}
          className="px-4 py-2 text-sm font-medium text-white bg-indigo-600 hover:bg-indigo-700 disabled:bg-indigo-400 rounded-lg transition-colors"
        >
          {dispatching ? 'Dispatching...' : 'Run Experiment'}
        </button>
        {dispatchResult && (
          <div className={`p-2 rounded text-sm ${
            dispatchResult.success
              ? 'bg-green-50 border border-green-200 text-green-800'
              : 'bg-red-50 border border-red-200 text-red-800'
          }`}>
            {dispatchResult.message}
          </div>
        )}
      </div>

      {/* Tabs */}
      <div className="mb-4 flex gap-2 border-b border-gray-200 pb-2">
        <button
          onClick={() => setViewMode('proposal')}
          className={`px-3 py-1.5 text-sm font-medium rounded-t ${
            viewMode === 'proposal'
              ? 'bg-blue-600 text-white'
              : 'bg-gray-100 text-gray-700 hover:bg-gray-200'
          }`}
        >
          Proposal
        </button>

        <button
          onClick={() => setViewMode('experiments')}
          className={`px-3 py-1.5 text-sm font-medium rounded-t ${
            viewMode === 'experiments'
              ? 'bg-blue-600 text-white'
              : 'bg-gray-100 text-gray-700 hover:bg-gray-200'
          }`}
        >
          Experiments{proposalExperiments.length > 0 ? ` (${proposalExperiments.length})` : ''}
        </button>

        {codeAvailable && (
          <button
            onClick={() => setViewMode('code')}
            className={`px-3 py-1.5 text-sm font-medium rounded-t ${
              viewMode === 'code'
                ? 'bg-blue-600 text-white'
                : 'bg-gray-100 text-gray-700 hover:bg-gray-200'
            }`}
          >
            Code
          </button>
        )}
      </div>

      {/* Content display */}
      {viewMode === 'code' ? (
        proposalExperiments[0]?.id ? (
          <div
            className="border border-gray-200 rounded-lg overflow-hidden"
            style={{
              height: 'calc(100vh - 300px)',
              width: '100vw',
              marginLeft: 'calc(-50vw + 50%)',
              marginRight: 'calc(-50vw + 50%)',
              maxWidth: 'none'
            }}
          >
            <CodeViewer
              experimentId={proposalExperiments[0].id}
              apiUrl={apiUrl}
              onClose={() => setViewMode('proposal')}
              embedded={true}
            />
          </div>
        ) : (
          <div className="bg-gray-50 p-8 rounded-lg text-center text-gray-500">
            No experiment selected. Run an experiment first to browse code.
          </div>
        )
      ) : viewMode === 'experiments' ? (
        <div>
          {experimentsLoading ? (
            <div className="text-gray-500 text-center py-8">Loading experiments...</div>
          ) : proposalExperiments.length === 0 ? (
            <div className="bg-gray-50 p-8 rounded-lg text-center text-gray-500">
              No experiments have been run for this proposal yet.
            </div>
          ) : (
            <div className="overflow-hidden rounded-lg border border-gray-200">
              <table className="min-w-full divide-y divide-gray-200">
                <thead className="bg-gray-50">
                  <tr>
                    <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">ID</th>
                    <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Run</th>
                    <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Status</th>
                    <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Worker</th>
                    <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Created</th>
                    <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Completed</th>
                    <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Cost</th>
                    <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Links</th>
                  </tr>
                </thead>
                <tbody className="bg-white divide-y divide-gray-200">
                  {proposalExperiments.map((exp) => (
                    <Fragment key={exp.id}>
                    <tr
                      className={`hover:bg-gray-50 cursor-pointer ${expandedExperimentId === exp.id ? 'bg-blue-50' : ''}`}
                      onClick={() => toggleExperimentLogs(exp.id)}
                    >
                      <td className="px-4 py-3 text-sm font-mono font-medium text-gray-900">
                        <span className={`inline-block transition-transform mr-1 ${expandedExperimentId === exp.id ? 'rotate-90' : ''}`}>&#9656;</span>
                        {exp.id}
                      </td>
                      <td className="px-4 py-3 text-sm text-gray-700">#{exp.run_number}</td>
                      <td className="px-4 py-3">
                        <span className={`inline-flex items-center gap-1.5 px-2 py-0.5 rounded text-xs font-medium ${
                          exp.status === 'completed' ? 'bg-green-100 text-green-800' :
                          exp.status === 'failed' ? 'bg-red-100 text-red-800' :
                          exp.status === 'running' ? 'bg-blue-100 text-blue-800' :
                          exp.status === 'cancelled' ? 'bg-yellow-100 text-yellow-800' :
                          'bg-gray-100 text-gray-800'
                        }`}>
                          {exp.status === 'running' && (
                            <div className="w-1.5 h-1.5 rounded-full bg-blue-500 animate-pulse" />
                          )}
                          {exp.status}
                        </span>
                      </td>
                      <td className="px-4 py-3 text-sm font-mono text-gray-500">{exp.worker_id || '—'}</td>
                      <td className="px-4 py-3 text-sm text-gray-500">
                        {new Date(exp.created_at).toLocaleString()}
                      </td>
                      <td className="px-4 py-3 text-sm text-gray-500">
                        {exp.completed_at ? new Date(exp.completed_at).toLocaleString() : '—'}
                      </td>
                      <td className="px-4 py-3 text-sm text-gray-500">
                        {exp.cost_actual != null ? `$${exp.cost_actual.toFixed(2)}` : exp.cost_estimate != null ? `~$${exp.cost_estimate.toFixed(2)}` : '—'}
                      </td>
                      <td className="px-4 py-3 text-sm">
                        <div className="flex items-center gap-2">
                          {exp.wandb_url && (
                            <a href={exp.wandb_url} target="_blank" rel="noopener noreferrer" className="text-blue-600 hover:text-blue-800 text-xs underline" onClick={(e) => e.stopPropagation()}>W&B</a>
                          )}
                          {exp.results && (
                            <span className="text-xs text-green-600" title={JSON.stringify(exp.results, null, 2)}>Has results</span>
                          )}
                          {exp.error && (
                            <span className="text-xs text-red-600" title={exp.error}>Error</span>
                          )}
                        </div>
                      </td>
                    </tr>
                    {expandedExperimentId === exp.id && (
                      <tr>
                        <td colSpan={8} className="p-0">
                          <div className="bg-gray-900 border-t border-gray-700">
                            <div className="px-4 py-2 bg-gray-800 flex items-center justify-between">
                              <span className="text-sm font-mono text-gray-300">
                                Logs for experiment {exp.id}
                              </span>
                              <div className="flex items-center gap-3">
                                <span className="text-xs text-gray-400">
                                  {eventsLoading ? 'Loading...' : `${experimentEvents.length} events`}
                                </span>
                                <span className="inline-flex items-center gap-1 text-xs text-green-400">
                                  <span className="w-1.5 h-1.5 rounded-full bg-green-400 animate-pulse" />
                                  Live
                                </span>
                              </div>
                            </div>
                            <div ref={inlineLogRef} className="p-4 overflow-auto max-h-80 font-mono text-xs">
                              {eventsLoading ? (
                                <div className="text-gray-400 text-center py-4">Loading logs...</div>
                              ) : experimentEvents.length === 0 ? (
                                <div className="text-gray-400 text-center py-4">No events recorded for this experiment.</div>
                              ) : (
                                experimentEvents.map((event, idx) => (
                                  <div
                                    key={idx}
                                    className={`${
                                      event.type.includes('error') || event.type.includes('fail') ? 'text-red-400' :
                                      event.type.includes('warn') ? 'text-yellow-400' :
                                      event.type.includes('start') || event.type.includes('creat') ? 'text-blue-400' :
                                      event.type.includes('complet') || event.type.includes('success') ? 'text-green-400' :
                                      'text-gray-300'
                                    }`}
                                  >
                                    [{new Date(event.created_at).toLocaleString()}] [{event.type}]{event.worker_id ? ` [${event.worker_id}]` : ''} {event.summary}
                                  </div>
                                ))
                              )}
                            </div>
                          </div>
                        </td>
                      </tr>
                    )}
                    </Fragment>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </div>
      ) : (
        <div className="prose prose-sm max-w-none">
          <ReactMarkdown
            remarkPlugins={[remarkGfm, remarkMath]}
            rehypePlugins={[rehypeKatex]}
          >
            {proposalContent}
          </ReactMarkdown>
        </div>
      )}
    </div>
  )
}

// Main Router Component
export default function ProposalsView({ apiUrl }: ProposalsViewProps) {
  const location = useLocation()

  // Check if we're viewing a specific proposal (e.g., /proposals/029-something)
  const pathParts = location.pathname.split('/').filter(Boolean)
  const proposalId = pathParts.length > 1 && pathParts[0] === 'proposals' ? pathParts[1] : null

  if (proposalId) {
    return <ProposalDetail apiUrl={apiUrl} proposalId={proposalId} />
  }

  return <ProposalsList apiUrl={apiUrl} />
}
